"use client";

//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'
import "./globals.css";

import {PrivyProvider} from '@privy-io/react-auth';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrivyProvider
          appId={process.env.NEXT_PUBLIC_PRIVY_APP_ID || ''}
          config={{
            // Customize Privy's appearance in your app
            appearance: {
              theme: 'light',
              accentColor: '#55ffac',
              logo: 'https://blockbocado.vercel.app/logo.png',
            },
            // Create embedded wallets for users who don't have a wallet
            embeddedWallets: {
              createOnLogin: 'users-without-wallets',
            },
          }}
        >
            <div className="bg-gradient-to-b from-[#55ffac] via-[#9eff7c] to-[#d9ff56]">
              {children}
            </div>
        </PrivyProvider>
      </body>
    </html>
  );
}
