import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-b from-[#55ffac] via-[#9eff7c] to-[#d9ff56]">
          {children}
        </div>
      </body>
    </html>
  );
}
